### ISSUE TITLE
Sample-app Error message

### ISSUE THREAD

**Issue by WORLD8848** [OneUIProject/oneui-design#7]
I am doing various Issue Solving in the process of applying the OneUIProject library.

I am in the process of resolving [java.lang.IllegalStateException: item_layout.xml is not disclosed as @Input] Issue.

In this process, when I go back to the beginning and run oneui-design, the following error message occurs. Do you happen to know why this error is occurring?

E/SeslBaseReflector: SOUND_TIME_PICKER_FAST NoSuchMethodException
    java.lang.NoSuchFieldException: SOUND_TIME_PICKER_FAST
        at java.lang.Class.getField(Class.java:1604)
        at androidx.reflect.SeslBaseReflector.getField(SeslBaseReflector.java:205)
        at androidx.reflect.media.SeslAudioManagerReflector.getField_SOUND_TIME_PICKER_SCROLL_FAST(SeslAudioManagerReflector.java:61)
        at androidx.picker.widget.SeslNumberPickerSpinnerDelegate.<init>(SeslNumberPickerSpinnerDelegate.java:521)
        at androidx.picker.widget.SeslNumberPicker.<init>(SeslNumberPicker.java:150)
        at androidx.picker.widget.SeslNumberPicker.<init>(SeslNumberPicker.java:144)
        at androidx.picker.widget.SeslNumberPicker.<init>(SeslNumberPicker.java:140)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at dev.oneuiproject.oneuiexample.base.BaseFragment.onCreateView(BaseFragment.java:24)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2989)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:122)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3157)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3101)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8231)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3872)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/SeslBaseReflector: SOUND_TIME_PICKER_SLOW NoSuchMethodException
    java.lang.NoSuchFieldException: SOUND_TIME_PICKER_SLOW
        at java.lang.Class.getField(Class.java:1604)
        at androidx.reflect.SeslBaseReflector.getField(SeslBaseReflector.java:205)
        at androidx.reflect.media.SeslAudioManagerReflector.getField_SOUND_TIME_PICKER_SCROLL_SLOW(SeslAudioManagerReflector.java:76)
        at androidx.picker.widget.SeslNumberPickerSpinnerDelegate.<init>(SeslNumberPickerSpinnerDelegate.java:522)
        at androidx.picker.widget.SeslNumberPicker.<init>(SeslNumberPicker.java:150)
        at androidx.picker.widget.SeslNumberPicker.<init>(SeslNumberPicker.java:144)
        at androidx.picker.widget.SeslNumberPicker.<init>(SeslNumberPicker.java:140)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at dev.oneuiproject.oneuiexample.base.BaseFragment.onCreateView(BaseFragment.java:24)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2989)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:122)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3157)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3101)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8231)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3872)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/SeslBaseReflector: setFastAudioOpenMode NoSuchMethodException
    java.lang.NoSuchMethodException: com.samsung.android.media.SemSoundAssistantManager.setFastAudioOpenMode [boolean]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at androidx.reflect.SeslBaseReflector.getDeclaredMethod(SeslBaseReflector.java:112)
        at androidx.reflect.media.SeslSemSoundAssistantManagerReflector.setFastAudioOpenMode(SeslSemSoundAssistantManagerReflector.java:67)
        at androidx.picker.widget.SeslNumberPickerSpinnerDelegate.<init>(SeslNumberPickerSpinnerDelegate.java:523)
        at androidx.picker.widget.SeslNumberPicker.<init>(SeslNumberPicker.java:150)
        at androidx.picker.widget.SeslNumberPicker.<init>(SeslNumberPicker.java:144)
        at androidx.picker.widget.SeslNumberPicker.<init>(SeslNumberPicker.java:140)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at dev.oneuiproject.oneuiexample.base.BaseFragment.onCreateView(BaseFragment.java:24)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2989)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:122)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3157)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3101)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8231)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3872)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
W/sec.sesl.teste: Accessing hidden method Landroid/view/View;->hidden_semSetDirectPenInputEnabled(Z)V (greylist, reflection, allowed)
E/SeslBaseReflector: SOUND_TIME_PICKER_FAST NoSuchMethodException 

.................
................

**Comment by salvogiangri** [comment]
This warning is irrelevant since it happens on non-Samsung OS or Samsung devices that have not OneUI 4 or above.

**Comment by WORLD8848** [comment]
OK!!

Thanks!!
